### ISSUE TITLE
(Django 4.1) Error templates.E003 during system check

### ISSUE THREAD

**Issue by filippotp** [hakib/django-admin-lightweight-date-hierarchy#12]
* django-admin-lightweight-date-hierarchy version: 1.0.1
* Django version: 4.1
* Python version: 3.10.5
* Operating System: Windows 10

### Description

After updating Django to version 4.1, the system check procedure throws error templates.E003 because of duplicate "admin_list" template tag module.

### What I Did

command launched:

python manage.py runserver 8000

end of stacktrace:

django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
?: (templates.E003) 'admin_list' is used for multiple template tag modules: 'django.contrib.admin.templatetags.admin_list', 'django_admin_lightweight_date_hierarchy.templatetags.admin_list'

System check identified 1 issue (0 silenced).

**Comment by ernestasga** [comment]
Have you found a solution by any chance?

**Comment by filippotp** [comment]
I temporarily solved the problem by removing `django_admin_lightweight_date_hierarchy` from the `INSTALLED_APPS` in the project settings and adding a custom template tag that calls the original function from the package:

```
from django import template
from django_admin_lightweight_date_hierarchy.templatetags.admin_list import date_hierarchy as default_date_hierarchy

register = template.Library()

@register.inclusion_tag('admin/date_hierarchy.html')
def date_hierarchy(cl):
    return default_date_hierarchy(cl)
```
